import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('/home/zhao/Downloads/Summary_Pack_new/Catalase/Catalase model');

model.label('14Nov2023_catalaseArticle_ksd.mph');

model.param.set('atip', ['1.8 [' native2unicode(hex2dec({'00' 'b5'}), 'unicode') 'm]']);
model.param.set('d', ['500 [' native2unicode(hex2dec({'00' 'b5'}), 'unicode') 'm]']);
model.param.set('f', 'F/R/T');
model.param.set('F', '96500 [C/mol]');
model.param.set('R', '8.314 [J/mol/K]');
model.param.set('T', '293 [K]');
model.param.set('Etip', '-0.4[V]');
model.param.set('Echa', '0.2 [V]');
model.param.set('Cha0', '0[mmol/L]');
model.param.set('ksc', '0.015 [cm/s]');
model.param.set('ksd', '1E4 [cm*L/(s*mol)]');
model.param.set('al', '0.5');
model.param.set('Chad0', '10 [mmol/L]');
model.param.set('x', '1E-6[m]');
model.param.set('re', '5.22 [nm]');

model.component.create('comp1', false);

model.component('comp1').geom.create('geom1', 2);

model.component('comp1').curvedInterior(false);

model.result.table.create('tbl137', 'Table');
model.result.table.create('tbl140', 'Table');
model.result.table.create('tbl141', 'Table');
model.result.table.create('tbl142', 'Table');
model.result.table.create('tbl143', 'Table');
model.result.table.create('tbl145', 'Table');
model.result.table.create('tbl146', 'Table');
model.result.table.create('tbl147', 'Table');
model.result.table.create('tbl148', 'Table');
model.result.table.create('tbl150', 'Table');
model.result.table.create('tbl155', 'Table');
model.result.table.create('tbl156', 'Table');
model.result.table.create('tbl157', 'Table');
model.result.table.create('tbl158', 'Table');
model.result.table.create('tbl159', 'Table');
model.result.table.create('tbl160', 'Table');
model.result.table.create('tbl161', 'Table');
model.result.table.create('tbl164', 'Table');
model.result.table.create('tbl165', 'Table');
model.result.table.create('tbl166', 'Table');
model.result.table.create('tbl167', 'Table');
model.result.table.create('tbl169', 'Table');
model.result.table.create('tbl171', 'Table');
model.result.table.create('tbl172', 'Table');
model.result.table.create('tbl173', 'Table');
model.result.table.create('tbl177', 'Table');
model.result.table.create('tbl178', 'Table');
model.result.table.create('tbl179', 'Table');
model.result.table.create('tbl180', 'Table');
model.result.table.create('tbl181', 'Table');
model.result.table.create('tbl182', 'Table');
model.result.table.create('tbl186', 'Table');
model.result.table.create('tbl188', 'Table');

model.component('comp1').geom('geom1').axisymmetric(true);

model.component('comp1').mesh.create('mesh1');

model.component('comp1').geom('geom1').lengthUnit([native2unicode(hex2dec({'00' 'b5'}), 'unicode') 'm']);
model.component('comp1').geom('geom1').repairTol(1.0E-5);
model.component('comp1').geom('geom1').repairTolType('auto');
model.component('comp1').geom('geom1').create('r1', 'Rectangle');
model.component('comp1').geom('geom1').feature('r1').set('pos', [0 450]);
model.component('comp1').geom('geom1').feature('r1').set('size', [25 100]);
model.component('comp1').geom('geom1').create('r2', 'Rectangle');
model.component('comp1').geom('geom1').feature('r2').set('pos', {'0' 'd'});
model.component('comp1').geom('geom1').feature('r2').set('size', {'10*atip' '1000-d'});
model.component('comp1').geom('geom1').create('co1', 'Compose');
model.component('comp1').geom('geom1').feature('co1').set('repairtoltype', 'relative');
model.component('comp1').geom('geom1').feature('co1').set('repairtol', 1.0E-6);
model.component('comp1').geom('geom1').feature('co1').set('formula', 'r1-r2');
model.component('comp1').geom('geom1').create('r3', 'Rectangle');
model.component('comp1').geom('geom1').feature('r3').set('pos', {'0' 'd-14'});
model.component('comp1').geom('geom1').feature('r3').set('size', {'atip' '14'});
model.component('comp1').geom('geom1').create('c1', 'Circle');
model.component('comp1').geom('geom1').feature('c1').set('selresult', true);
model.component('comp1').geom('geom1').feature('c1').set('selresultshow', 'bnd');
model.component('comp1').geom('geom1').feature('c1').set('pos', {'0' 'd-re-x'});
model.component('comp1').geom('geom1').feature('c1').set('rot', 270);
model.component('comp1').geom('geom1').feature('c1').set('r', 0.00522);
model.component('comp1').geom('geom1').feature('c1').set('angle', 180);
model.component('comp1').geom('geom1').create('c2', 'Circle');
model.component('comp1').geom('geom1').feature('c2').set('selresult', true);
model.component('comp1').geom('geom1').feature('c2').set('selresultshow', 'bnd');
model.component('comp1').geom('geom1').feature('c2').set('pos', {'0' 'd-re-x'});
model.component('comp1').geom('geom1').feature('c2').set('rot', 60);
model.component('comp1').geom('geom1').feature('c2').set('r', 0.00522);
model.component('comp1').geom('geom1').feature('c2').set('angle', 30);
model.component('comp1').geom('geom1').run;
model.component('comp1').geom('geom1').run('fin');

model.component('comp1').selection.create('sel1', 'Explicit');
model.component('comp1').selection('sel1').geom('geom1', 1);
model.component('comp1').selection('sel1').set([1 3 5 6 7 8]);
model.component('comp1').selection.create('int1', 'Intersection');
model.component('comp1').selection('int1').set('entitydim', 1);
model.component('comp1').selection.create('dif1', 'Difference');
model.component('comp1').selection('dif1').set('entitydim', 1);
model.component('comp1').selection('sel1').set('groupcontang', true);
model.component('comp1').selection('int1').set('input', {'geom1_c1_bnd' 'geom1_c2_bnd'});
model.component('comp1').selection('dif1').set('add', {'int1'});
model.component('comp1').selection('dif1').set('subtract', {'sel1'});

model.view.create('view2', 3);
model.view.create('view3', 3);
model.view.create('view4', 3);
model.view.create('view5', 3);
model.view.create('view6', 3);
model.view.create('view7', 3);
model.view.create('view8', 3);
model.view.create('view9', 3);
model.view.create('view10', 3);
model.view.create('view11', 3);
model.view.create('view12', 3);
model.view.create('view13', 3);
model.view.create('view14', 3);
model.view.create('view15', 3);
model.view.create('view16', 3);

model.component('comp1').physics.create('tds', 'DilutedSpecies', 'geom1');
model.component('comp1').physics('tds').field('concentration').field('cha');
model.component('comp1').physics('tds').field('concentration').component({'cha' 'chad' 'prod'});
model.component('comp1').physics('tds').selection.set([1 2]);
model.component('comp1').physics('tds').create('fl1', 'Fluxes', 1);
model.component('comp1').physics('tds').feature('fl1').selection.set([9]);
model.component('comp1').physics('tds').create('fl2', 'Fluxes', 1);
model.component('comp1').physics('tds').feature('fl2').selection.set([16]);

model.component('comp1').mesh('mesh1').create('ftri1', 'FreeTri');
model.component('comp1').mesh('mesh1').feature('ftri1').create('size1', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri1').create('size2', 'Size');
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').selection.geom('geom1', 2);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').selection.set([2]);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size2').selection.geom('geom1', 2);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size2').selection.set([1]);

model.result.table('tbl137').label('0-100');
model.result.table('tbl137').comments('Line Integration 2');
model.result.table('tbl140').label('101-190');
model.result.table('tbl140').comments('Line Integration 1');
model.result.table('tbl141').label('191-256');
model.result.table('tbl141').comments('Line Integration 1');
model.result.table('tbl142').label('257-327');
model.result.table('tbl142').comments('Line Integration 1');
model.result.table('tbl143').label('327-400');
model.result.table('tbl143').comments('Line Integration 1');
model.result.table('tbl145').label('401-600');
model.result.table('tbl145').comments('Line Integration 1');
model.result.table('tbl146').label('600-746');
model.result.table('tbl146').comments('Line Integration 1');
model.result.table('tbl147').comments('Line Integration 1');
model.result.table('tbl148').label('RW1');
model.result.table('tbl148').comments('Line Integration 1');
model.result.table('tbl150').label('RW2');
model.result.table('tbl150').comments('-');
model.result.table('tbl155').label('RW3part1');
model.result.table('tbl155').comments('Line Integration 1');
model.result.table('tbl156').label('RW3part2');
model.result.table('tbl156').comments('Line Integration 1');
model.result.table('tbl157').label('RW4');
model.result.table('tbl157').comments('Line Integration 1');
model.result.table('tbl158').label('RW4 after explicit selection');
model.result.table('tbl158').comments('Line Integration 1');
model.result.table('tbl159').label('ksd at 10 nm');
model.result.table('tbl159').comments('Line Integration 1');
model.result.table('tbl160').label('ksd at 100 nm');
model.result.table('tbl160').comments('Line Integration 1');
model.result.table('tbl161').label('ksd at 1000nm');
model.result.table('tbl161').comments('Line Integration 1');
model.result.table('tbl164').label('RW 7ms part1');
model.result.table('tbl164').comments('Line Integration 1');
model.result.table('tbl165').label('RW 7ms part 2');
model.result.table('tbl165').comments('Line Integration 1');
model.result.table('tbl166').label('RW 7ms part 3');
model.result.table('tbl166').comments('Line Integration 1');
model.result.table('tbl167').label('RW 7ms part 4');
model.result.table('tbl167').comments('Line Integration 1');
model.result.table('tbl169').label('RW 7ms part 5 r');
model.result.table('tbl169').comments('Line Integration 1');
model.result.table('tbl171').label('Before applying CV parameters');
model.result.table('tbl171').comments('Line Integration 1');
model.result.table('tbl172').label('After applying CV parameters');
model.result.table('tbl172').comments('Line Integration 1');
model.result.table('tbl173').label('Arc Angle');
model.result.table('tbl173').comments('Line Integration 1');
model.result.table('tbl177').label('Random walk 0p1 ms part 1');
model.result.table('tbl177').comments('Line Integration 1');
model.result.table('tbl178').label('Random walk 0p1 ms part 2');
model.result.table('tbl178').comments('Line Integration 1');
model.result.table('tbl179').label('Random walk 0p1 ms part 3');
model.result.table('tbl179').comments('Line Integration 1');
model.result.table('tbl180').label('Random walk 1  ms part 3');
model.result.table('tbl180').comments('Line Integration 1');
model.result.table('tbl181').label('Random walk 7 ms part 3');
model.result.table('tbl181').comments('Line Integration 1');
model.result.table('tbl182').label('Random walk 7 ms ');
model.result.table('tbl182').comments('Line Integration 1');
model.result.table('tbl186').label('Flux on Enzyme Ksd');
model.result.table('tbl186').comments('Line Integration 2');
model.result.table('tbl188').label('Test');
model.result.table('tbl188').comments('Line Integration 1');

model.thermodynamics.label('Thermodynamics Package');

model.component('comp1').view('view1').axis.set('xmin', -0.008435960859060287);
model.component('comp1').view('view1').axis.set('xmax', 0.11700839549303055);
model.component('comp1').view('view1').axis.set('ymin', 498.9203186035156);
model.component('comp1').view('view1').axis.set('ymax', 499.0248718261719);

model.component('comp1').physics('tds').prop('MassConsistentStabilization').set('glim_mass', '(0.1[mol/m^3])/tds.helem');
model.component('comp1').physics('tds').prop('AdvancedSettings').set('BackCompState', 0);
model.component('comp1').physics('tds').prop('TransportMechanism').set('VolatilizationInPartiallySaturatedPorousMedia', true);
model.component('comp1').physics('tds').prop('TransportMechanism').set('Convection', false);
model.component('comp1').physics('tds').feature('sp1').label('Species Properties');
model.component('comp1').physics('tds').feature('cdm1').set('minput_temperature_src', 'userdef');
model.component('comp1').physics('tds').feature('cdm1').set('D_cha', {'1.76*(10^-9)'; '0'; '0'; '0'; '1.76*(10^-9)'; '0'; '0'; '0'; '1.76*(10^-9)'});
model.component('comp1').physics('tds').feature('cdm1').set('D_chad', {'1.71*(10^-9)'; '0'; '0'; '0'; '1.71*(10^-9)'; '0'; '0'; '0'; '1.71*(10^-9)'});
model.component('comp1').physics('tds').feature('cdm1').set('D_prod', {'1.71*(10^-9)'; '0'; '0'; '0'; '1.71*(10^-9)'; '0'; '0'; '0'; '1.71*(10^-9)'});
model.component('comp1').physics('tds').feature('nflx1').set('IncludeConvection', true);
model.component('comp1').physics('tds').feature('init1').set('initc', {'Cha0'; 'Chad0'; '0'});
model.component('comp1').physics('tds').feature('dcont1').set('pairDisconnect', true);
model.component('comp1').physics('tds').feature('dcont1').label('Continuity');
model.component('comp1').physics('tds').feature('fl1').set('species', [1; 0; 1]);
model.component('comp1').physics('tds').feature('fl1').set('N0', {'ksc*(prod*exp(al*f*(Etip-Echa))-cha*exp(-al*f*(Etip-Echa)))'; '-ksc*(prod*exp(al*f*(Etip-Echa))-cha*exp(-al*f*(Etip-Echa)))'; '-ksc*(prod*exp(al*f*(Etip-Echa))-cha*exp(-al*f*(Etip-Echa)))'});
model.component('comp1').physics('tds').feature('fl2').set('species', [1; 1; 0]);
model.component('comp1').physics('tds').feature('fl2').set('N0', {'ksd*chad*chad'; '-2*ksd*chad*chad'; '0'});

model.component('comp1').mesh('mesh1').feature('size').set('hauto', 1);
model.component('comp1').mesh('mesh1').feature('size').set('table', 'cfd');
model.component('comp1').mesh('mesh1').feature('ftri1').set('smoothmaxiter', 8);
model.component('comp1').mesh('mesh1').feature('ftri1').set('smoothmaxdepth', 8);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('custom', 'on');
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('table', 'cfd');
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hmax', 1.13);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hmin', 0.05);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hnarrow', 6);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hnarrowactive', true);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hgrad', 1.15);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hmaxactive', false);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hminactive', false);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hcurveactive', false);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size1').set('hgradactive', false);
model.component('comp1').mesh('mesh1').feature('ftri1').feature('size2').set('table', 'cfd');
model.component('comp1').mesh('mesh1').run;

model.study.create('std1');
model.study('std1').create('param', 'Parametric');
model.study('std1').create('time', 'Transient');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('t1', 'Time');
model.sol('sol1').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('t1').create('d1', 'Direct');
model.sol('sol1').feature('t1').create('i1', 'Iterative');
model.sol('sol1').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').create('sl1', 'SORLine');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').create('sl1', 'SORLine');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature.remove('fcDef');
model.sol.create('sol2');
model.sol('sol2').study('std1');
model.sol('sol2').label('Parametric Solutions 1');
model.sol.create('sol49');
model.sol('sol49').study('std1');
model.sol('sol49').label('Parametric Solutions 2');
model.sol.create('sol59');
model.sol('sol59').study('std1');
model.sol('sol59').label('Parametric Solutions 3');
model.sol.create('sol228');
model.sol('sol228').study('std1');
model.sol('sol228').label('Parametric Solutions 4');

model.result.dataset.create('rev1', 'Revolve2D');
model.result.numerical.create('int1', 'IntLine');
model.result.numerical.create('int2', 'IntLine');
model.result.numerical('int1').selection.set([9]);
model.result.numerical('int1').set('probetag', 'none');
model.result.numerical('int2').selection.set([16]);
model.result.numerical('int2').set('probetag', 'none');
model.result.create('pg1', 'PlotGroup2D');
model.result.create('pg2', 'PlotGroup2D');
model.result.create('pg3', 'PlotGroup3D');
model.result.create('pg4', 'PlotGroup2D');
model.result.create('pg5', 'PlotGroup3D');
model.result.create('pg6', 'PlotGroup2D');
model.result.create('pg7', 'PlotGroup3D');
model.result('pg1').set('data', 'dset3');
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').create('str1', 'Streamline');
model.result('pg1').feature('surf1').set('expr', 'chad');
model.result('pg2').create('surf1', 'Surface');
model.result('pg2').create('str1', 'Streamline');
model.result('pg2').create('surf2', 'Surface');
model.result('pg3').create('vol1', 'Volume');
model.result('pg4').create('surf1', 'Surface');
model.result('pg4').create('str1', 'Streamline');
model.result('pg4').feature('surf1').set('expr', 'chad');
model.result('pg5').create('vol1', 'Volume');
model.result('pg5').feature('vol1').set('expr', 'chad');
model.result('pg6').create('surf1', 'Surface');
model.result('pg6').create('str1', 'Streamline');
model.result('pg6').feature('surf1').set('expr', 'prod');
model.result('pg7').create('surf1', 'Surface');
model.result('pg7').feature('surf1').set('expr', 'prod');

model.study('std1').feature('param').active(false);
model.study('std1').feature('param').set('sweeptype', 'filled');
model.study('std1').feature('param').set('pname', {'x'});
model.study('std1').feature('param').set('plistarr', {'1E-8 2.5E-9 6.63015E-8 1.80074E-7 2.5E-9 6.12362E-7 1.21278E-6 1.33938E-6 2.38987E-6 1.97194E-6 1.29801E-6 1.52463E-6 1.94738E-6 2.06325E-6 2.61756E-6 3.01274E-6 3.2936E-6 3.39002E-6 2.78464E-6 1.62665E-6 1.81036E-6 1.67036E-6 2.52222E-6 2.01507E-6 2.06419E-6 1.48502E-6 2.57256E-8 5.839E-7 2.5E-9 2.69392E-7 2.5E-9 9.23097E-7 6.2754E-7 2.21721E-6 2.07744E-6 3.19527E-6 3.81712E-6 4.4188E-6 5.67009E-6 5.37144E-6 5.02133E-6 5.64778E-6 5.41487E-6 5.11821E-6 5.46697E-6 5.56358E-6 6.5335E-6 6.38326E-6 6.60436E-6 7.22702E-6 7.29792E-6 6.02045E-6 6.85907E-6 6.71957E-6 6.58935E-6 5.5309E-6 4.42919E-6 3.88186E-6 4.0557E-6 4.25682E-6 3.82349E-6 4.14873E-6 3.55192E-6 3.76873E-6 3.72219E-6 2.97914E-6 3.87285E-6 4.00373E-6 4.136E-6 4.49304E-6 6.04317E-6 5.55574E-6 4.45556E-6 3.97534E-6 3.13224E-6 2.45779E-6 3.75227E-6 3.36055E-6 3.17289E-6 4.73663E-6 4.40725E-6 4.47171E-6 4.97436E-6 4.99715E-6 5.16201E-6 4.03767E-6 3.54925E-6 3.57776E-6 3.42661E-6 3.85384E-6 4.2612E-6 4.4848E-6 4.16366E-6 3.3298E-6 2.87425E-6 1.13525E-6 1.20252E-6 8.84158E-7 2.14083E-6 2.73114E-6 1.67682E-6 1.13665E-6 1.53175E-6 1.50905E-6 3.47312E-7 2.5E-9 7.26253E-7 2.26395E-6 2.30995E-6 3.71726E-6 4.69812E-6 3.91568E-6 4.82265E-6 4.69384E-6 4.70226E-6 3.61459E-6 4.00697E-6 5.05083E-6 4.24377E-6 3.54417E-6 3.5876E-6 3.90673E-6 4.56182E-6 5.18916E-6 5.18456E-6 5.02468E-6 5.8008E-6 4.98433E-6 5.08252E-6 5.22326E-6 4.91555E-6 6.66235E-6 6.6519E-6 7.53519E-6 7.51714E-6 8.09934E-6 7.70489E-6 8.16929E-6 8.65077E-6 9.55244E-6 9.25452E-6 1.00935E-5 8.2568E-6'});
model.study('std1').feature('param').set('punit', {'m'});
model.study('std1').feature('param').set('probesel', 'none');
model.study('std1').feature('param').set('romtagsuffix', 'parnamevalnz');
model.study('std1').feature('time').set('tunit', [native2unicode(hex2dec({'00' 'b5'}), 'unicode') 's']);
model.study('std1').feature('time').set('tlist', '1 100 1000 7000');

model.sol('sol1').attach('std1');
model.sol('sol1').feature('st1').label('Compile Equations: Time Dependent');
model.sol('sol1').feature('v1').label('Dependent Variables 1.1');
model.sol('sol1').feature('v1').set('clist', {'1 100 1000 7000' ['6.999[' native2unicode(hex2dec({'00' 'b5'}), 'unicode') 's]']});
model.sol('sol1').feature('t1').label('Time-Dependent Solver 1.1');
model.sol('sol1').feature('t1').set('tunit', [native2unicode(hex2dec({'00' 'b5'}), 'unicode') 's']);
model.sol('sol1').feature('t1').set('tlist', '1 100 1000 7000');
model.sol('sol1').feature('t1').set('rtol', 0.005);
model.sol('sol1').feature('t1').set('maxorder', 2);
model.sol('sol1').feature('t1').set('stabcntrl', true);
model.sol('sol1').feature('t1').feature('dDef').label('Direct 2');
model.sol('sol1').feature('t1').feature('aDef').label('Advanced 1');
model.sol('sol1').feature('t1').feature('aDef').set('cachepattern', true);
model.sol('sol1').feature('t1').feature('fc1').label('Fully Coupled 1.1');
model.sol('sol1').feature('t1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 8);
model.sol('sol1').feature('t1').feature('fc1').set('damp', '0.9');
model.sol('sol1').feature('t1').feature('fc1').set('jtech', 'once');
model.sol('sol1').feature('t1').feature('fc1').set('stabacc', 'aacc');
model.sol('sol1').feature('t1').feature('fc1').set('aaccdim', 5);
model.sol('sol1').feature('t1').feature('fc1').set('aaccmix', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('aaccdelay', 1);
model.sol('sol1').feature('t1').feature('d1').label('Direct, concentrations (tds)');
model.sol('sol1').feature('t1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('t1').feature('i1').label('AMG, concentrations (tds)');
model.sol('sol1').feature('t1').feature('i1').set('maxlinit', 50);
model.sol('sol1').feature('t1').feature('i1').feature('ilDef').label('Incomplete LU 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').label('Multigrid 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('maxcoarsedof', 50000);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').label('Presmoother 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('soDef').label('SOR 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('iter', 1);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('linerelax', 0.7);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').label('Postsmoother 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('soDef').label('SOR 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').label('SOR Line 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linesweeptype', 'ssor');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('iter', 1);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('linerelax', 0.7);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('sl1').set('relax', 0.5);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').label('Coarse Solver 1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('dDef').label('Direct 2');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').label('Direct 1.1');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').runAll;

model.result.dataset('rev1').set('startangle', -90);
model.result.dataset('rev1').set('revangle', 225);
model.result.numerical('int1').set('table', 'tbl188');
model.result.numerical('int1').set('expr', {'(tds.ndflux_prod)*96500[C/mol]'});
model.result.numerical('int1').set('unit', {'A'});
model.result.numerical('int1').set('descr', {''});
model.result.numerical('int1').set('intsurface', true);
model.result.numerical('int2').set('expr', {'(tds.ndflux_chad)*6.0221E23[1/mol]' '(tds.ndflux_chad)'});
model.result.numerical('int2').set('unit', {'1/s' 'mol/s'});
model.result.numerical('int2').set('descr', {'' ''});
model.result.numerical('int2').set('intsurface', true);
model.result.numerical('int1').setResult;
model.result('pg1').label('Concentration, cha (tds)');
% model.result('pg1').set('looplevel', [1 1]);
model.result('pg1').set('titletype', 'custom');
model.result('pg1').set('prefixintitle', 'Species cha:');
model.result('pg1').feature('surf1').set('resolution', 'normal');
model.result('pg1').feature('str1').set('posmethod', 'uniform');
model.result('pg1').feature('str1').set('pointtype', 'arrow');
model.result('pg1').feature('str1').set('arrowcount', 7);
model.result('pg1').feature('str1').set('arrowlength', 'logarithmic');
model.result('pg1').feature('str1').set('arrowscale', 2.1696489832926771E49);
model.result('pg1').feature('str1').set('color', 'gray');
model.result('pg1').feature('str1').set('recover', 'pprint');
model.result('pg1').feature('str1').set('arrowcountactive', false);
model.result('pg1').feature('str1').set('arrowscaleactive', false);
model.result('pg1').feature('str1').set('resolution', 'normal');
model.result('pg2').label('Concentration, cha (tds) 1');
model.result('pg2').set('titletype', 'custom');
model.result('pg2').set('prefixintitle', 'Species cha:');
model.result('pg2').feature('surf1').set('descr', 'Concentration');
model.result('pg2').feature('surf1').set('resolution', 'normal');
model.result('pg2').feature('str1').set('posmethod', 'uniform');
model.result('pg2').feature('str1').set('pointtype', 'arrow');
model.result('pg2').feature('str1').set('arrowcount', 24);
model.result('pg2').feature('str1').set('arrowlength', 'logarithmic');
model.result('pg2').feature('str1').set('arrowscale', 3.230467149762628E9);
model.result('pg2').feature('str1').set('color', 'gray');
model.result('pg2').feature('str1').set('recover', 'pprint');
model.result('pg2').feature('str1').set('arrowcountactive', false);
model.result('pg2').feature('str1').set('arrowscaleactive', false);
model.result('pg2').feature('str1').set('resolution', 'normal');
model.result('pg2').feature('surf2').set('resolution', 'normal');
model.result('pg3').label('Concentration, cha, 3D (tds)');
model.result('pg3').set('titletype', 'custom');
model.result('pg3').set('prefixintitle', 'Species cha:');
model.result('pg3').set('typeintitle', false);
model.result('pg3').feature('vol1').set('resolution', 'normal');
model.result('pg4').label('Concentration, chad (tds)');
model.result('pg4').set('titletype', 'custom');
model.result('pg4').set('prefixintitle', 'Species chad:');
model.result('pg4').feature('surf1').set('resolution', 'normal');
model.result('pg4').feature('str1').set('expr', {'tds.tflux_chadr' 'tds.tflux_chadz'});
model.result('pg4').feature('str1').set('posmethod', 'uniform');
model.result('pg4').feature('str1').set('pointtype', 'arrow');
model.result('pg4').feature('str1').set('arrowcount', 19);
model.result('pg4').feature('str1').set('arrowlength', 'logarithmic');
model.result('pg4').feature('str1').set('arrowscale', 5425296.007482203);
model.result('pg4').feature('str1').set('color', 'gray');
model.result('pg4').feature('str1').set('recover', 'pprint');
model.result('pg4').feature('str1').set('arrowcountactive', false);
model.result('pg4').feature('str1').set('arrowscaleactive', false);
model.result('pg4').feature('str1').set('resolution', 'normal');
model.result('pg5').label('Concentration, chad, 3D (tds)');
model.result('pg5').set('titletype', 'custom');
model.result('pg5').set('prefixintitle', 'Species chad:');
model.result('pg5').set('typeintitle', false);
model.result('pg5').feature('vol1').set('resolution', 'normal');
model.result('pg6').label('Concentration, prod (tds)');
model.result('pg6').set('titletype', 'custom');
model.result('pg6').set('prefixintitle', 'Species prod:');
model.result('pg6').feature('surf1').set('resolution', 'normal');
model.result('pg6').feature('str1').set('expr', {'tds.tflux_prodr' 'tds.tflux_prodz'});
model.result('pg6').feature('str1').set('posmethod', 'uniform');
model.result('pg6').feature('str1').set('pointtype', 'arrow');
model.result('pg6').feature('str1').set('arrowlength', 'logarithmic');
model.result('pg6').feature('str1').set('color', 'gray');
model.result('pg6').feature('str1').set('recover', 'pprint');
model.result('pg6').feature('str1').set('resolution', 'normal');
model.result('pg7').label('Concentration, prod, 3D (tds)');
model.result('pg7').set('titletype', 'custom');
model.result('pg7').set('prefixintitle', 'Species prod:');
model.result('pg7').set('typeintitle', false);
model.result('pg7').feature('surf1').set('resolution', 'normal');